apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: network-foundation

spec:
  type: terraform
  domain: platform-foundation
  subscribe:
    environments:
      - name: development
        profile: pull-request
      - name: staging
        profile: verify
      - name: production
        profile: release
  parameters:
    stackName: network-foundation
    terraformDir: .
    terraformVersion: 1.9.8
  labels:
    team: platform
    layer: foundation
    stack: network