version: 2

project_name: liteci

builds:
  - id: entrypoint
    dir: cmd/liteci
    binary: entrypoint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
