apiVersion: orun.io/v1
kind: Stack
metadata:
  name: sumo-ops-orun-platform-stack
  title: Sumo Ops Platform Orun Stack
  version: 0.9.2
  description: Packaged compositions for the Sumo Ops Platform Orun repository.
  owner: sourceplane
  tags:
    - terraform
    - helm
    - cloudflare
    - platform
registry:
  host: ghcr.io
  namespace: sourceplane
  repository: sumo-ops-platform-orun-stack
  visibility: public
