apiVersion: sourceplane.io/v1
kind: ComponentTree
metadata:
    intent: examples/gha-actions/intent.yaml
    generatedAt: "2026-04-22T10:27:28Z"
discovery:
    roots:
        - services
components:
    - name: local-gha-demo
      type: gha-demo
      domain: platform
      enabled: false
      path: services/local-gha-demo
      subscribe:
        environments:
            - development
      labels:
        team: platform
        tier: example
      source: discovered
      sourcePath: services/local-gha-demo/component.yaml
      fileSize: 236
      fileModTime: "2026-04-18T05:06:31.967875411Z"
