apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: commerce-checkout-values

spec:
  type: helm-values
  domain: commerce-checkout
  subscribe:
    environments:
      - development
      - production
  inputs:
    chartPath: ../../charts/chart-2/chart
    valuesFile: values.yaml
    releaseName: commerce-checkout
    helmVersion: v3.15.4
  labels:
    team: platform
    layer: delivery
    domain: commerce
    release: commerce-checkout
  dependsOn:
    - component: cluster-addons