apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: cluster-addons

spec:
  type: terraform
  domain: platform-foundation
  subscribe:
    environments:
      - name: development
        profile: pull-request
      - name: staging
        profile: verify
      - name: production
        profile: release
  inputs:
    stackName: cluster-addons
    terraformDir: .
    terraformVersion: 1.9.8
  labels:
    team: platform
    layer: foundation
    stack: cluster
  dependsOn:
    - component: network-foundation